# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20171006_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='plants',
            name='latitude',
            field=models.CharField(default='1', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='plants',
            name='longitude',
            field=models.CharField(default='1', max_length=10, null=True),
        ),
    ]
