# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20171010_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plants',
            name='latitude',
            field=models.CharField(default='13.06075027268141', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='plants',
            name='longitude',
            field=models.CharField(default='80.255126953125', max_length=50, null=True),
        ),
    ]
