# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20171010_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plants',
            name='latitude',
            field=models.CharField(default='28.555576049185973', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='plants',
            name='longitude',
            field=models.CharField(default='77.16796875', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='currentplant',
            field=models.IntegerField(default=-1),
        ),
    ]
