# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20171022_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='plants',
            name='actuatorstatus',
            field=models.IntegerField(default=0),
        ),
    ]
