# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_plants_actuatorstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='plants',
            name='actuatorcontrol',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plants',
            name='actuatorlink',
            field=models.CharField(default='-1', max_length=200),
        ),
    ]
