# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0014_weathersensors_rain'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantsensors',
            name='latitude',
            field=models.CharField(default='1', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='plantsensors',
            name='longitude',
            field=models.CharField(default='1', max_length=10, null=True),
        ),
    ]
