# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 18:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0015_auto_20171010_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantsensors',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='plantsensors',
            name='longitude',
        ),
    ]
